meta:
  schema-version: 0.1.0
  created-on: "2024-04-05T13:30:29Z"
  cli-version: 0.2.0
projects:
  tdg-ninja-nodegoat:
    targets:
      - package.json
    manager:
      ecosystem: node
      name: npm
      version: "7"
    overrides:
      set-value:
        0.4.3:
          use: 0.4.3-sp1
        2.0.0:
          use: 2.0.0-sp1
      glob-parent:
        3.1.0:
          use: 3.1.0-sp1
      qs:
        6.5.2:
          use: 6.5.2-sp1
      bson:
        1.0.9:
          use: 1.0.9-sp1
      getobject:
        0.1.0:
          use: 0.1.0-sp1
      growl:
        1.9.2:
          use: 1.9.2-sp1
      minimist:
        1.2.0:
          use: 1.2.0-sp1
        0.0.10:
          use: 0.0.10-sp1
        1.2.5:
          use: 1.2.5-sp1
        0.0.8:
          use: 0.0.8-sp1
      minimatch:
        3.0.4:
          use: 3.0.4-sp1
      lodash:
        4.17.11:
          use: 4.17.11-sp1
      json-schema:
        0.2.3:
          use: 0.2.3-sp1
      got:
        6.7.1:
          use: 6.7.1-sp1
      decode-uri-component:
        0.2.0:
          use: 0.2.0-sp1
      ansi-regex:
        3.0.0:
          use: 3.0.0-sp1
      hoek:
        2.16.3:
          use: 2.16.3-sp1
      ini:
        1.3.5:
          use: 1.3.5-sp1
